
CREATE NONCLUSTERED INDEX [IDX_S_TLM_DAT] ON [ICMPSS].[S_TLM_DAT]
(
	[VRB_COD] ASC,
	[TLM_DAT_TMS] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO


CREATE UNIQUE NONCLUSTERED INDEX [M_ABR_UK] ON [ICMMET].[M_ABR]
(
	[ABR_CDE] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [M_ABR_UK1]    Script Date: 1/27/2021 3:59:40 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [M_ABR_UK1] ON [ICMMET].[M_ABR]
(
	[ABR_FOR] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_S_TLM_DAT_HST] ON [ICMPSS].[S_TLM_DAT_HST]
(
	[VRB_COD] ASC,
	[TLM_DAT_TMS] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, DROP_EXISTING = OFF, ONLINE = OFF) ON [PRIMARY]
GO


CREATE NONCLUSTERED INDEX [IDX_D_EQI] ON [ICMPCM].[D_EQI]
(
	[STD_EQI_COD],[TET_COD],[STE_COD] ASC
)
GO

CREATE NONCLUSTERED INDEX [f_eqi_pmr_atl_tms_idx] ON [ICMPCM].[F_EQI_PMR_ATL]
(
	[PMR_TMS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

create index f_eqi_pmr_atl_tms_include on icmpcm.f_eqi_pmr_atl (pmr_tms) include
(tet_id , ste_id , eqi_id, pmr_id, sce_eqi_pmr_uom_id, sns_tag_id );
go